# Context Lint on Vercel/Netlify preview deployments
# Triggers when a deployment succeeds and lints the preview URL.
name: Context Lint (Preview Deploy)

on:
  deployment_status:

jobs:
  context-lint:
    if: github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Context Lint on Preview
        uses: hanselhansel/context-cli@main
        with:
          url: ${{ github.event.deployment_status.target_url }}
          fail-under: '50'
          single-page: 'true'
