# Basic Context Lint workflow
# Runs on every push to main and on pull requests.
# Fails the build if the LLM readiness score drops below 60.
name: Context Lint

on:
  push:
    branches: [main]
  pull_request:

jobs:
  context-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Context Lint
        uses: hanselhansel/context-cli@main
        with:
          url: 'https://your-site.com'
          fail-under: '60'
